## NumPy Bascis 
##### Learn Python for Data Science Interactively at www.DataCamp.com

The NumPy library is the core library for scientfic computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays.

In [1]:
import numpy as np

### Creating Arrays

In [2]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [4]:
b = np.array([(1.5,2,3), (4,5,6)], dtype=float)
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [5]:
c = np.array([[(1.5,2,3),(4,5,6)],[(3,2,1),(4,5,6)]],dtype=float)
c

array([[[1.5, 2. , 3. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 1. ],
        [4. , 5. , 6. ]]])

#### Initial Placeholders

In [6]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
np.ones((2,3,4),dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [10]:
d = np.arange(10,25,5)
d

array([10, 15, 20])

In [11]:
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [12]:
e = np.full((2,2),7)
e

array([[7, 7],
       [7, 7]])

In [13]:
f = np.eye(2)
f

array([[1., 0.],
       [0., 1.]])

In [14]:
np.random.random((2,2))

array([[0.22116518, 0.5441624 ],
       [0.33639316, 0.02388278]])

In [15]:
np.empty((3,2))

array([[1.5, 2. ],
       [3. , 4. ],
       [5. , 6. ]])

### I/O

In [16]:
np.save('my_arr',a)

In [17]:
np.savez('my_arr2.npz',a,b)

In [18]:
np.load('my_arr.npy')

array([1, 2, 3])

In [20]:
np.savetxt("myarr.txt",a,delimiter=" ")

In [21]:
np.loadtxt("myarr.txt")

array([1., 2., 3.])

In [ ]:
np.genfromtext("myfile.csv", delimiter=',')

### Data Types

In [28]:
np.int64 #Signed 64bit int
np.float32 #floating point
np.complex # 128 floats
np.bool #True or False
np.object #Python Object
np.string_ #fixed-length string type
np.unicode_ #fixed-length unicode type

numpy.str_

### Inspecting Array

In [29]:
a.shape #array dimensions

(3,)

In [30]:
len(a) #Length of array

3

In [31]:
b.ndim #Number of array dimensions

2

In [32]:
e.size #Number of array elements

4

In [33]:
b.dtype #data type

dtype('float64')

In [34]:
b.dtype.name

'float64'

In [35]:
b.astype(int) # Convert to different type

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
np.info(np.ndarray.dtype) #Help

Data-type of the array's elements.

Parameters
----------
None

Returns
-------
d : numpy dtype object

See Also
--------
numpy.dtype

Examples
--------
>>> x
array([[0, 1],
       [2, 3]])
>>> x.dtype
dtype('int32')
>>> type(x.dtype)
<type 'numpy.dtype'>


## Array Mathematics

### Arithmetic Operations

In [37]:
g = a-b #subtraction
g

array([[-0.5,  0. ,  0. ],
       [-3. , -3. , -3. ]])

In [38]:
np.subtract(a,b)

array([[-0.5,  0. ,  0. ],
       [-3. , -3. , -3. ]])

In [39]:
b+a

array([[2.5, 4. , 6. ],
       [5. , 7. , 9. ]])

In [40]:
np.add(b,a)

array([[2.5, 4. , 6. ],
       [5. , 7. , 9. ]])

In [41]:
a/b

array([[0.66666667, 1.        , 1.        ],
       [0.25      , 0.4       , 0.5       ]])

In [42]:
np.divide(a,b)

array([[0.66666667, 1.        , 1.        ],
       [0.25      , 0.4       , 0.5       ]])

In [43]:
a*b

array([[ 1.5,  4. ,  9. ],
       [ 4. , 10. , 18. ]])

In [44]:
np.multiply(a,b)

array([[ 1.5,  4. ,  9. ],
       [ 4. , 10. , 18. ]])

In [45]:
np.exp(b) #exponentiation

array([[  4.48168907,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

In [46]:
np.sqrt(b) # square root

array([[1.22474487, 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [47]:
np.sin(a) # sines of an array

array([0.84147098, 0.90929743, 0.14112001])

In [48]:
np.cos(a) # cosine

array([ 0.54030231, -0.41614684, -0.9899925 ])

In [49]:
np.log(a)

array([0.        , 0.69314718, 1.09861229])

In [50]:
e.dot(f) # Dot product

array([[7., 7.],
       [7., 7.]])

### Comparison

In [51]:
a == b

array([[False,  True,  True],
       [False, False, False]])

In [52]:
a < 2

array([ True, False, False])

In [53]:
np.array_equal(a,b)

False

### Aggregate Function

In [54]:
a.sum()

6

In [55]:
a.min()

1

In [56]:
b.max(axis=0)

array([4., 5., 6.])

In [57]:
b.cumsum(axis=1)

array([[ 1.5,  3.5,  6.5],
       [ 4. ,  9. , 15. ]])

In [58]:
a.mean()

2.0

In [63]:
np.median(b)

3.5

In [64]:
np.corrcoef(a)

1.0

In [65]:
np.std(b)

1.5920810978785667

### Copying Arrays

In [67]:
h = a.view()
h

array([1, 2, 3])

In [68]:
np.copy(a)

array([1, 2, 3])

In [69]:
h = a.copy()
h

array([1, 2, 3])

### Sorting Arrays

In [71]:
a.sort()
a

array([1, 2, 3])

In [73]:
c.sort(axis=0)
c

array([[[1.5, 2. , 1. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 3. ],
        [4. , 5. , 6. ]]])

### Subsetting, Slicing, Indexing

In [74]:
a[2] #Subsetting

3

In [75]:
b[1,2] 

6.0

In [76]:
a[0:2] #Slicing

array([1, 2])

In [77]:
b[0:2,1]

array([2., 5.])

In [78]:
b[:1]

array([[1.5, 2. , 3. ]])

In [79]:
c[1,...]

array([[3., 2., 3.],
       [4., 5., 6.]])

In [80]:
a[::-1]

array([3, 2, 1])

In [81]:
a[a<2] #Boolean Indexing

array([1])

In [82]:
b[[1,0,1,0],[0,1,2,0]] #Fancy Indexing

array([4. , 2. , 6. , 1.5])

In [83]:
b[[1,0,1,0,]][:,[0,1,2,0]]

array([[4. , 5. , 6. , 4. ],
       [1.5, 2. , 3. , 1.5],
       [4. , 5. , 6. , 4. ],
       [1.5, 2. , 3. , 1.5]])

## Array Manipulation

In [84]:
i = np.transpose(b)
i

array([[1.5, 4. ],
       [2. , 5. ],
       [3. , 6. ]])

In [88]:
b.ravel() #Changing Array Shape

array([1.5, 2. , 3. , 4. , 5. , 6. ])

In [86]:
g.reshape(3,-2)

array([[-0.5,  0. ],
       [ 0. , -3. ],
       [-3. , -3. ]])

In [89]:
np.resize(h,(2,6))

array([[1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3]])

In [93]:
np.insert(a,1,5)

array([1, 5, 2, 3])

In [95]:
np.delete(a,[1])

array([1, 3])

In [98]:
np.concatenate((a,d),axis=0)

array([ 1,  2,  3, 10, 15, 20])

In [99]:
np.vstack((a,b)) # Stack arrays vertically(row-wise)

array([[1. , 2. , 3. ],
       [1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [100]:
np.r_[e,f] # Stack arrays vertically(row-wise)

array([[7., 7.],
       [7., 7.],
       [1., 0.],
       [0., 1.]])

In [101]:
np.hstack((e,f)) # Stack arrays horizontally(column-wise)

array([[7., 7., 1., 0.],
       [7., 7., 0., 1.]])

In [102]:
np.column_stack((a,d)) #Create stacked column-wise array

array([[ 1, 10],
       [ 2, 15],
       [ 3, 20]])

In [103]:
np.c_[a,d]

array([[ 1, 10],
       [ 2, 15],
       [ 3, 20]])

In [104]:
np.hsplit(a,3) #Split the array horizontally at the 3rd index

[array([1]), array([2]), array([3])]

In [105]:
np.vsplit(c,2) #Split the array vertically at the 2nd index

[array([[[1.5, 2. , 1. ],
         [4. , 5. , 6. ]]]), array([[[3., 2., 3.],
         [4., 5., 6.]]])]